<?php
use Magento\Framework\App\Action\Action;
?>
<?php
/**
 *
 * @var $block \ISM\Blog\Block\Items
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var $__call \Magento\Framework\Exception\LocalizedException
 */
?>

<?php
$_postsCollection = $block->getProductCollection();
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_postsCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
    }
    $pos = $block->getPositioned();
    ?>
<div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
    <ol class="posts">
        <?php foreach ($_postsCollection as $_post): ?>
            <a class="post" href="<?php echo 'blog/index/view/id/' . $_post->getEntityId() ?>">
                <h2 class="post-title"><?=$block->escapeHtml($_post->getTitle())?></h2>
                <p class="post-content"><b>Content:</b> <br/><?=$block->escapeHtml($_post->getContent())?></p>
                <p class="post-announce"><b>Announce:</b><br/><?=$block->escapeHtml($_post->getAnnounce())?></p>
                <h4 class="post-date"><?=$block->escapeHtml(rtrim($_post->getPublishedDate(),"00:00:00"))?></h4>
            </a>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
