<?php
/**
 * Product list template
 * @var \Magento\Framework\Escaper $escaper
 * @var $block \ISM\Blog\Block\Page\Item */
?>
<?php
    $_postInfo = $block->getPost();
?>
<?php if ($_postInfo === null): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
    }
    $pos = $block->getPositioned();
    ?>
<div <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <div class="item-content">
            <h1 class="item-title"><?= $_postInfo->getData('title') ?></h1>
            <p class="para"><b>Announce:</b><?= $_postInfo->getData('announce') ?></p>
            <p class="para"><b>Content:</b><?= $_postInfo->getData('content') ?></p>
            <time><?= rtrim($_postInfo->getData('published_date'), "00:00:00") ?></time>
        </div>
</div>
<?php endif; ?>



